### ISSUE TITLE
Not loading categories

### ISSUE THREAD

**Issue by iamonuwa** [imusify/imusify-web#128]
**Describe the bug**
Error loading categories.

**To Reproduce**
1. Load up the app
2. Categories are not loaded

**Expected behavior**
Categories are loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/6551094/47614756-10bbc400-daa5-11e8-9b0e-abf3298e33c4.png)

![image](https://user-images.githubusercontent.com/6551094/47614761-3052ec80-daa5-11e8-8449-af1531cedacd.png)

**Web (please complete the following information):**
 - OS: Mac OSX
 - Browser Chrome
 - Version 69.0.3497.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chovy** [comment]
This is not a bug. I had to import the categories.
