### ISSUE TITLE
Format tracks and artists titles

### ISSUE THREAD

**Issue by iamonuwa** [imusify/imusify-web#143]
**Describe the bug**
Format tracks and artists titles. Truncate titles to make it consistent

**To Reproduce**
1.Load the app
2. On the tracks view, the horizontal scrollbar is longer
3. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6551094/47856372-5949e900-dde7-11e8-9899-2748363926c2.png)

**Web (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chovy** [comment]
should just add a css elipsis to the title field.
