### ISSUE TITLE
Increase the left padding on filters/subfilters

### ISSUE THREAD

**Issue by outwork** [imusify/imusify-web#40]
![screen shot 2018-09-11 at 21 37 04](https://user-images.githubusercontent.com/18143389/45380377-37b05a80-b60b-11e8-879d-0eb88b559f32.png)

Try `padding-left: 2.5rem`

**Comment by chovy** [comment]
@outwork what do you mean by filters/subfilters?

**Comment by outwork** [comment]
@chovy `.tags, .categories ` classes

**Comment by chovy** [comment]
thanks
