### ISSUE TITLE
Custom scrollbar

### ISSUE THREAD

**Issue by outwork** [imusify/imusify-web#43]
![screen shot 2018-09-11 at 21 38 19](https://user-images.githubusercontent.com/18143389/45380914-8e6a6400-b60c-11e8-850a-758ed0aaa49b.png)

**Comment by chovy** [comment]
@outwork not sure what   you're implying here.

**Comment by chovy** [comment]
its a bad idea to implement custom scrollbars
you can't ensure it will work everywhere
native scrollbar is best
