### ISSUE TITLE
Padding between tracks is wrong on huge screens

### ISSUE THREAD

**Issue by outwork** [imusify/imusify-web#50]
On my 2k resolution the padding between tracks is wrong. Check the screenshot:
![screen shot 2018-09-11 at 21 57 58](https://user-images.githubusercontent.com/18143389/45381389-dfc72300-b60d-11e8-9bc6-b050905eed50.png)

**Comment by chovy** [comment]
after PR gets merged can you check again?

**Comment by outwork** [comment]
sure, i will do @chovy

**Comment by outwork** [comment]
still not working.

**Comment by chovy** [comment]
ok, how are you reproducing this?

**Comment by chovy** [comment]
i might have to debug on your machine over a screensharing app
